# Generated by Django 4.2.3 on 2023-12-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=100)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT'), ('MOBILE PHONES', 'MOBILE PHONES')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
